export enum WaitingRoomEvents {
    CreateRoom = 'waitingRoom:createRoom',
    JoinRoom = 'waitingRoom:joinRoom',
    LeaveRoom = 'waitingRoom:leaveRoom',
    KickPlayer = 'waitingRoom:kickPlayer',
    StartGame = 'waitingRoom:startGame',
    GetAvailableRooms = 'waitingRoom:getAvailableRooms',
    RoomCreated = 'waitingRoom:roomCreated',
    RoomUpdated = 'waitingRoom:roomUpdated',
    RoomLocked = 'waitingRoom:roomLocked',
    RoomUnlocked = 'waitingRoom:roomUnlocked',
    YouWereKicked = 'waitingRoom:youWereKicked',
    OrganizerLeft = 'waitingRoom:organizerLeft',
    GameStarted = 'waitingRoom:gameStarted',
    AvailableRooms = 'waitingRoom:availableRooms',
    RoomsUpdated = 'waitingRoom:roomsUpdated',
    AddVirtualPlayer = 'waitingRoom:addVirtualPlayer',
    RemoveVirtualPlayer = 'waitingRoom:removeVirtualPlayer',
}
