export const SANCTUARY_REACTIVATION_DELAY_IN_TURNS = 3;
export const SANCTUARY_DOUBLE_OR_NOTHING_WIN_PROBABILITY = 0.5;
export const SANCTUARY_DOUBLE_OR_NOTHING_MULTIPLIER = 2;
export const SANCTUARY_NORMAL_MULTIPLIER = 1;
export const SANCTUARY_NO_EFFECT_MULTIPLIER = 0;
export const SANCTUARY_SANTE_BASE_HEAL_AMOUNT = 2;
export const SANCTUARY_COMBAT_BASE_BONUS_AMOUNT = 1;
export const SANCTUARY_SIDE_LENGTH = 2;
