export enum MatchEvents {
    GameState = 'gamePlay:gameState',
    TurnStarted = 'gamePlay:turnStarted',
    ReachableCells = 'gamePlay:reachableCells',
    RequestReachables = 'gamePlay:reachableCells',
    PlayerMoved = 'gamePlay:playerMoved',
    TurnEnded = 'gamePlay:turnEnded',
    CombatStarted = 'gamePlay:combatStarted',
    CombatResult = 'gamePlay:combatResult',
    CombatEnded = 'gamePlay:combatEnded',
    DoorToggled = 'gamePlay:doorToggled',
    PlayerAbandoned = 'gamePlay:playerAbandoned',
    GameOver = 'gamePlay:gameOver',
    RequestMove = 'gamePlay:requestMove',
    RequestAttack = 'gamePlay:requestAttack',
    RequestToggleDoor = 'gamePlay:requestToggleDoor',
    EndTurn = 'gamePlay:endTurn',
    Abandon = 'gamePlay:abandon',
    ToggleDebugMode = 'gamePlay:toggleDebugMode',
    RequestTeleport = 'gamePlay:requestTeleport',
    DebugEndTurn = 'gamePlay:debugEndTurn',
    DebugModeToggled = 'gamePlay:debugModeToggled',
    MatchLocked = 'gamePlay:locked',
    StartMatch = 'gamePlay:startMatch',
    MatchStarted = 'gamePlay:matchStarted',
    RequestFlagTransfer = 'gamePlay:requestFlagTransfer',
    FlagTransferRequest = 'gamePlay:flagTransferRequest',
    FlagTransferResponse = 'gamePlay:flagTransferResponse',
    FlagTransferred = 'gamePlay:flagTransferred',
    FlagPickedUp = 'gamePlay:flagPickedUp',
    FlagDropped = 'gamePlay:flagDropped',
    FlagTransferCancelled = 'gamePlay:flagTransferCancelled',
    FlagTransferDeclined = 'gamePlay:flagTransferDeclined',
    WrongStartPoint = 'gamePlay:wrongStartPoint',
    ActionConsumed = 'gamePlay:actionConsumed',
    ChoosePosture = 'gamePlay:choosePosture',
    CombatRoundResult = 'gamePlay:combatRoundResult',
    RequestSanctuaryInteraction = 'gamePlay:requestSanctuaryInteraction',
    SanctuaryInteractionResult = 'gamePlay:sanctuaryInteractionResult',
    SanctuaryReactivated = 'gamePlay:sanctuaryReactivated',
    RoundEnded = 'combat: roundEnded',
    PlayersUpdate = 'gamePlay:newPlayersInfo',
    CombatInformation = 'combat:Information',
}

export enum TimerEvents {
    Timeout = "gamePlaye:timeout",
    StopTimer = "gamePlay:stopTimer",
    Tick = "gamePlay:Tick",
    StartingMatch = 'starting match',
    NextTurn = 'gamePlay:NextTurn',
    StartTransition = 'gamePlay:transitionBegin',
    CombatTick = 'gamePlay:combatTick',
}